### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by rillian**
Hey, thanks for maintaining linux tools for these boards!

Here are some simple clean up patches:
- Fix two warnings.
- Remove generated autotool stuff from the repo.

Hope you'll consider them.

### CODE REVIEW

**Comment by katie-snow** [comment]
Thanks for cleaning up the warnings.  I need to look into the removing of generated files.  When I have removed them locally I have run into issues.

**Comment by OzFalcon** [comment]
The "autogen.sh" script seems to work fine on my Debian (Stretch) system.

The "autogen.sh" script on my Arch Linux system showed some warnings but it did compile.
** I'll post the warning in the next post, I can't remember what it was now.

**Comment by rillian** [comment]
Thanks!

**Comment by katie-snow** [comment]
Thank you for cleaning up the auto files.

**Pull request merged**
